name: Build OpenSSH for Android 64-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Android SDK and NDK
        run: |
          # Install dependencies
          sudo apt update
          sudo apt install -y wget unzip openjdk-11-jdk

          # Set up Android SDK
          mkdir -p $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk/cmdline-tools
          rm commandlinetools-linux-7583922_latest.zip

          # Accept licenses
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --licenses

          # Install Android platform tools, build tools, and NDK
          $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

          # Set environment variables for SDK and NDK
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "NDK_HOME=$HOME/Android/Sdk/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/platform-tools:$NDK_HOME:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt install -y autoconf automake build-essential libssl-dev zlib1g-dev

      - name: Download OpenSSH source code
        run: |
          git clone https://github.com/openssh/openssh-portable.git
          cd openssh-portable

      - name: Build OpenSSH for Android
        run: |
          cd openssh-portable
          # Set the NDK and configure for Android build
          ./configure --host=arm-linux-androideabi --prefix=$HOME/openssh-install
          make
          make install

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openssh-build
          path: $HOME/openssh-install
